apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: http
  replicas: 5
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: ghcr.io/rakshith-r/http_server:latest
        ports:
        - containerPort: 3000